// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app) {
    app.all('/*', function(req, res, next) {
      res.header('Access-Control-Allow-Origin', '*');
      res.header('Access-Control-Allow-Headers', 'X-Requested-With,Content-Type');
      res.header('Access-Control-Request-Method', 'GET,POST');
      return next();
    });
    return app.get('/', function(req, res) {
      return res.render('domainquery', {
        title: 'resolvedyet'
      });
    });
  };

}).call(this);
