// Generated by IcedCoffeeScript 1.4.0c
(function() {

  module.exports = function(io) {
    var dnsMonitor;
    dnsMonitor = require('./dns-monitor');
    return io.of('/resolvedyet').on('connection', function(socket) {
      socket.on('startmonitor', dnsMonitor.start);
      socket.on('connect', dnsMonitor.connect);
      return socket.on('disconnect', dnsMonitor.disconnect);
    });
  };

}).call(this);
